#! /bin/sh

# This instance of Cockpit is only accessed via the reverse proxy.
# The reverse proxy does SSL for us, so we configure Cockpit to only
# do plain HTTP.  To make this safe, we restrict it to only answer
# connections from localhost.

XDG_CONFIG_DIRS=$(dirname $0) /usr/libexec/cockpit-ws --address 127.0.0.1 --port 9999 --no-tls
